---
title: "Market making in simple random world"
---

We simulate profit of a market maker (MM) in a setting with simple assumptinons. We make the following assumptions:

- one traded asset
- one market maker
- prices (midpoints) are determined exogenously and follow a random walk without drift
- no trading costs
- unrestricted short selling
- MM has lower and upper limit on the inventory
- marketable (i.e. liquidity taking or aggressive) trade with volume of 1 arrives every cycle

Each cycle consists of these steps:

1. midpoint price either decreases or increases by one from its previous value, randomly and with equal probability (e.g. 100 -> 99, or 100 -> 101)
2. MM adjusts the bid and the ask, with bid-spead and ask-spread of 1 (e.g. midpoint = 100, bid = 99, ask = 101). If current inventory equals lower limit, the MM does not post the ask. If the current inventory equals upper limit, the MM does not post the bid.
3. A market order (volume always equal to 1) arrives. If the order is a buy and MM posted an ask, a trade occurs. If the market order is a sell and market maker had posted a bid, a trade occurs. 

We will simulate N = 10,000 cycles and look at the profit curve.

```{r, cache=TRUE}

random_prices <- function(n, start_price=100, rng_seed=123) {
    # Generate random prices, with lag-1 differences in {-1, 0, 1}
    #
    # Arguments:
    # n             number of prices to generate
    # start_price   the starting price
    # seed          seed to inialize the RNG with
    #
    # Returns:
    # random_prices     vector of length n, with random prices
    
    set.seed(rng_seed)
    return(cumsum(c(start_price, round(runif(n-1) * 2 - 1))))
}


allowed_trades <- function(aggro_orders, inventory_limits=c(-1, 1)) {
    # Returns a logical vector indicating which trades can be
    # executed without breaching inventory_limits.
    # Arguments:
    #           aggro_orders        a vector of values {-1, 1}, with -1 
    #                               representing an aggressive sell order (MM trades at the bid) 
    #                               and 1 representing aggressive buy order (MM trades at the ask)
    #           inventory_limits    a 2-value vector, e.g. (-5, 6) representing
    #                               the limits of inventory that the market maker
    #                               has to adhere to.
    # Returns:  
    #           allowed_trades      logical vector of same length as the trades argument, indicating
    #                               trades that the market maker can particiapte in without going 
    #                               past the inventory limits.
    # 
    n <- length(aggro_orders)
    allowed_trades <- rep(NA, n)  # pre-allocate
    lower <- min(inventory_limits)
    upper <- max(inventory_limits)
    
    inventory <- 0
    for (i in 1:n) {
        # a sell trade (-1) increases inventory, a buy (+1) decreases
        # hence we need to subtract the trade from current inventory
        # to get new inventory
        new_inventory <- inventory - aggro_orders[i] 
        if (new_inventory >= lower & new_inventory <= upper) {
            inventory <- new_inventory
            allowed_trades[i] <- TRUE
        } else {
            # inventory remains unchanged as MM does not trade
            allowed_trades[i] <- FALSE
        }
    }
    
    return(allowed_trades)
}


random_orders <- function(n, rng_seed=123) {
    # Generate buy and sell orders randomly
    #
    # Arguments:    
    # n       number of orders to generate
    # seed    seed to inialize the RNG with
    #
    # Returns:
    # random_orders     a vector of length n, with values in {-1, 1}
    #                   with -1 being a sell order and 1 a buy order
    set.seed(rng_seed)
    return(round(runif(n)) * 2 - 1)
}

N <- 10000
orders <- random_orders(N)
midpoints <- random_prices(N)
inventory_limits <- c(-1, 1)  
trades <- allowed_trades(orders, inventory_limits)

# compute the trade price (bid or ask) then compute the cash flow:
# because bid-spread is 1 and ask spread is 1, we can simply
# add midpoints and orders to get the execution prices. Then
# multiply the execution price by the orders to get the MM's 
# cash flow.
cash_flow <- (midpoints[trades] + orders[trades]) * orders[trades]
end_profit <- sum(cash_flow)
# visualize that paper profit
plot(cumsum(cash_flow), type='l',
     main=paste('Profit MM at the end:', end_profit))
plot(midpoints, type='l')
```
